### ISSUE TITLE
Compatible with ChartJS 3.6?

### ISSUE THREAD

**Issue by jproefrock** [Makanz/chartjs-plugin-trendline#59]
I'm getting some mixed messages here.  Your About says `Made for Chart.js > 2.0`, but your README.md says `Made for Chart.js 3.X`. However, your documentation on how to add it to a chart doesn't seem to work with v3.6.

Any thoughts?

I have a Stackblitz here that shows how I attempted to implement it.
https://stackblitz.com/edit/chart-js-version-3-ygaa31?file=src/app/app.component.ts

TYIA!

**Comment by mainettis** [comment]
It's compatible with Chart.js v3.6. If you load the scripts to the client browser and it has access to the window, it will register itself. You could use jsfiddle to see.

The problem you seem to be having, is with the export/import. It could be fixed by current pending pull request: https://github.com/Makanz/chartjs-plugin-trendline/pull/60 .
Though, it could also be an issue with the way angular works with CommonJS modules.

**Comment by Makanz** [comment]
A new update are in testing after I have merged two PR:s.
